# Generated by Django 3.2.25 on 2025-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20251106_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.BigIntegerField(default=0),
        ),
    ]
